AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle,setup}'
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
